export enum WordType {
  NOUN = 'NOUN',
  VERB = 'VERB',
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  PREPOSITION = 'PREPOSITION',
  CONJUNCTION = 'CONJUNCTION',
  INTERJECTION = 'INTERJECTION',
  NONE = 'NONE',
  ADJECTIVE_NUMERAL = "ADJECTIVE_NUMERAL",
  ADJECTIVE_NOUN = "ADJECTIVE_NOUN",
  ADJECTIVE_PRONOUN = "ADJECTIVE_PRONOUN",
  ADJECTIVE_NOUN_ALT = "ADJECTIVE_NOUN_ALT",
  ADVERB_NEGATIVE_MARKER = "ADVERB_NEGATIVE_MARKER",
  ADVERB_NOUN = "ADVERB_NOUN",
  INDEFINITE_ARTICLE = "INDEFINITE_ARTICLE",
  CONJUNCTION_SUBORDINATE_NEXUS = "CONJUNCTION_SUBORDINATE_NEXUS",
  SUBORDINATE_CONJUNCTION = "SUBORDINATE_CONJUNCTION",
  EXPRESSION = "EXPRESSION",
  IDIOMATIC_EXPRESSION = "IDIOMATIC_EXPRESSION",
  TEMPORAL_EXPRESSION = "TEMPORAL_EXPRESSION",
  PHRASE = "PHRASE",
  HABITUAL_IMPERFECT = "HABITUAL_IMPERFECT",
  IMPERATIVE_PLURAL = "IMPERATIVE_PLURAL",
  IMPERATIVE_SINGULAR = "IMPERATIVE_SINGULAR",
  PERIPHRASTIC_IMPERFECT = "PERIPHRASTIC_IMPERFECT",
  SIMPLE_IMPERFECT_SUFFIX = "SIMPLE_IMPERFECT_SUFFIX",
  LOCUTION = "LOCUTION",
  ADVERBIAL_LOCUTION = "ADVERBIAL_LOCUTION",
  ASPECTUAL_MARKER = "ASPECTUAL_MARKER",
  ASPECTUAL_MARKER_IMPERFECT = "ASPECTUAL_MARKER_IMPERFECT",
  EXISTENCE_MARKER = "EXISTENCE_MARKER",
  PRAGMATIC_MARKER = "PRAGMATIC_MARKER",
  PREVERBAL_ASPECTUAL_TEMPORAL_MARKER = "PREVERBAL_ASPECTUAL_TEMPORAL_MARKER",
  TEMPORAL_ASPECTUAL_MARKER = "TEMPORAL_ASPECTUAL_MARKER",
  TEMPORAL_ASPECTUAL_MARKER_ALT = "TEMPORAL_ASPECTUAL_MARKER_ALT",
  VERBAL_MARKER = "VERBAL_MARKER",
  VERBAL_ASPECTUAL_MARKER = "VERBAL_ASPECTUAL_MARKER",
  NEGATIVE_NULL = "NEGATIVE_NULL",
  SUBORDINATE_NEXUS = "SUBORDINATE_NEXUS",
  NUMBER = "NUMBER",
  PARTICIPLE = "PARTICIPLE",
  PREPOSITION_SUBORDINATE_NEXUS = "PREPOSITION_SUBORDINATE_NEXUS",
  SPANISH_BORROWING = "SPANISH_BORROWING",
  PRONOUN_PLURAL_ARTICLE = "PRONOUN_PLURAL_ARTICLE",
  PRONOUN_SUBORDINATE_CONJUNCTION = "PRONOUN_SUBORDINATE_CONJUNCTION",
  PRONOUN_INTERROGATIVE = "PRONOUN_INTERROGATIVE",
  PRONOUN_PREPOSITION_VERB = "PRONOUN_PREPOSITION_VERB",
  DEMONSTRATIVE_PRONOUN = "DEMONSTRATIVE_PRONOUN",
  INDEFINITE_PRONOUN = "INDEFINITE_PRONOUN",
  PERSONAL_PRONOUN = "PERSONAL_PRONOUN",
  PERSONAL_PRONOUN_ALT = "PERSONAL_PRONOUN_ALT",
  ENCLITIC_PERSONAL_PRONOUN = "ENCLITIC_PERSONAL_PRONOUN",
  RELATIVE_PRONOUN = "RELATIVE_PRONOUN",
  SUFFIX = "SUFFIX",
  NOUN_ADJECTIVE = "NOUN_ADJECTIVE",
  NOUN_DEROGATORY = "NOUN_DEROGATORY",
  COLLECTIVE_NOUN = "COLLECTIVE_NOUN",
  MASCULINE_FEMININE_NOUN = "MASCULINE_FEMININE_NOUN",
  PLURAL_NOUN = "PLURAL_NOUN",
  PROPER_NOUN = "PROPER_NOUN",
  NOUN_ADJECTIVE_ALT = "NOUN_ADJECTIVE_ALT",
  TITLE = "TITLE",
  ATONIC_VARIANT = "ATONIC_VARIANT",
  VERB_NOUN = "VERB_NOUN",
  COPULATIVE_VERB = "COPULATIVE_VERB",
  COPULATIVE_VERB_PRETERITE = "COPULATIVE_VERB_PRETERITE",
  COPULATIVE_VERB_VARIANT = "COPULATIVE_VERB_VARIANT",
  IMPERFECT_COPULATIVE_VERB = "IMPERFECT_COPULATIVE_VERB",
  PRESENT_COPULATIVE_VERB = "PRESENT_COPULATIVE_VERB",
  IMPERSONAL_VERB = "IMPERSONAL_VERB",
  INFINITIVE_VERB = "INFINITIVE_VERB",
  INFINITIVE_VERB_TEMPORAL_MARKER = "INFINITIVE_VERB_TEMPORAL_MARKER",
  INFINITIVE_VERB_COPULATIVE_VERB = "INFINITIVE_VERB_COPULATIVE_VERB",
  INTRANSITIVE_VERB = "INTRANSITIVE_VERB",
  IMPERFECT_MODAL_VERB = "IMPERFECT_MODAL_VERB",
  PRONOMINAL_VERB = "PRONOMINAL_VERB",
  REFLEXIVE_VERB = "REFLEXIVE_VERB",
  TRANSITIVE_VERB = "TRANSITIVE_VERB",
}

export const WORD_TYPE_SPANISH: Record<string, WordType> = {
  "Adjetivo": WordType.ADJECTIVE,
  "Adjetivo / Numeral": WordType.ADJECTIVE_NUMERAL,
  "Adjetivo / Sustantivo": WordType.ADJECTIVE_NOUN,
  "Adjetivo/Pronombre": WordType.ADJECTIVE_PRONOUN,
  "Adjetivo/Sustantivo": WordType.ADJECTIVE_NOUN_ALT,
  "Adverbio": WordType.ADVERB,
  "Adverbio / Marcador negativo": WordType.ADVERB_NEGATIVE_MARKER,
  "Adverbio / Sustantivo": WordType.ADVERB_NOUN,
  "Artículo indefinido": WordType.INDEFINITE_ARTICLE,
  "Conjunción": WordType.CONJUNCTION,
  "Conjunción / Nexo subordinante": WordType.CONJUNCTION_SUBORDINATE_NEXUS,
  "Conjunción subordinada": WordType.SUBORDINATE_CONJUNCTION,
  "Expresión": WordType.EXPRESSION,
  "Expresión idiomática": WordType.IDIOMATIC_EXPRESSION,
  "Expresión temporal": WordType.TEMPORAL_EXPRESSION,
  "Frase": WordType.PHRASE,
  "habitual en imperfecto": WordType.HABITUAL_IMPERFECT,
  "Imperativo plural": WordType.IMPERATIVE_PLURAL,
  "Imperativo singular": WordType.IMPERATIVE_SINGULAR,
  "Imperfecto perifrástico": WordType.PERIPHRASTIC_IMPERFECT,
  "imperfecto simple /  Sufijo": WordType.SIMPLE_IMPERFECT_SUFFIX,
  "Interjección": WordType.INTERJECTION,
  "Locución": WordType.LOCUTION,
  "Locución adverbial": WordType.ADVERBIAL_LOCUTION,
  "Marcador aspectual": WordType.ASPECTUAL_MARKER,
  "Marcador aspectual en imperfecto": WordType.ASPECTUAL_MARKER_IMPERFECT,
  "Marcador de existencia": WordType.EXISTENCE_MARKER,
  "Marcador pragmático": WordType.PRAGMATIC_MARKER,
  "Marcador preverbal aspectual temporal ": WordType.PREVERBAL_ASPECTUAL_TEMPORAL_MARKER,
  "Marcador temporal aspectual": WordType.TEMPORAL_ASPECTUAL_MARKER,
  "Marcador Temporal aspectual ": WordType.TEMPORAL_ASPECTUAL_MARKER_ALT,
  "Marcador verbal": WordType.VERBAL_MARKER,
  "Marcador verbal aspectual": WordType.VERBAL_ASPECTUAL_MARKER,
  "Negativo/Nulo": WordType.NEGATIVE_NULL,
  "Nexo subordinante": WordType.SUBORDINATE_NEXUS,
  "Número": WordType.NUMBER,
  "Participio": WordType.PARTICIPLE,
  "Preposición": WordType.PREPOSITION,
  "Preposición / Nexo subordinante ": WordType.PREPOSITION_SUBORDINATE_NEXUS,
  "Préstamo del español": WordType.SPANISH_BORROWING,
  "Pronombre / Artículo Plural": WordType.PRONOUN_PLURAL_ARTICLE,
  "Pronombre / Conjunción subordinada": WordType.PRONOUN_SUBORDINATE_CONJUNCTION,
  "Pronombre / Interrogativo": WordType.PRONOUN_INTERROGATIVE,
  "Pronombre / Preposición / Verbo": WordType.PRONOUN_PREPOSITION_VERB,
  "Pronombre demostrativo": WordType.DEMONSTRATIVE_PRONOUN,
  "Pronombre indefinido": WordType.INDEFINITE_PRONOUN,
  "Pronombre personal": WordType.PERSONAL_PRONOUN,
  "Pronombre Personal": WordType.PERSONAL_PRONOUN_ALT,
  "Pronombre personal (enclítico)": WordType.ENCLITIC_PERSONAL_PRONOUN,
  "Pronombre relativo": WordType.RELATIVE_PRONOUN,
  "Sufijo": WordType.SUFFIX,
  "Sustantivo": WordType.NOUN,
  "Sustantivo / Adjetivo": WordType.NOUN_ADJECTIVE,
  "Sustantivo / Despectivo": WordType.NOUN_DEROGATORY,
  "Sustantivo colectivo": WordType.COLLECTIVE_NOUN,
  "Sustantivo masculino/femenino": WordType.MASCULINE_FEMININE_NOUN,
  "Sustantivo plural": WordType.PLURAL_NOUN,
  "Sustantivo propio": WordType.PROPER_NOUN,
  "Sustantivo/Adjetivo": WordType.NOUN_ADJECTIVE_ALT,
  "Título": WordType.TITLE,
  "Variante átona": WordType.ATONIC_VARIANT,
  "Verbo": WordType.VERB,
  "Verbo / Sustantivo": WordType.VERB_NOUN,
  "Verbo copulativo": WordType.COPULATIVE_VERB,
  "Verbo copulativo (Pretérito)": WordType.COPULATIVE_VERB_PRETERITE,
  "Verbo copulativo / Variante ": WordType.COPULATIVE_VERB_VARIANT,
  "Verbo copulativo imperfecto": WordType.IMPERFECT_COPULATIVE_VERB,
  "Verbo copulativo presente": WordType.PRESENT_COPULATIVE_VERB,
  "Verbo impersonal": WordType.IMPERSONAL_VERB,
  "Verbo infinitivo": WordType.INFINITIVE_VERB,
  "Verbo infinitivo / Marcador temporal ": WordType.INFINITIVE_VERB_TEMPORAL_MARKER,
  "Verbo infinitivo / Verbo copulativo": WordType.INFINITIVE_VERB_COPULATIVE_VERB,
  "Verbo intransitivo": WordType.INTRANSITIVE_VERB,
  "Verbo modal en imperfecto": WordType.IMPERFECT_MODAL_VERB,
  "Verbo pronominal": WordType.PRONOMINAL_VERB,
  "Verbo reflexivo": WordType.REFLEXIVE_VERB,
  "Verbo transitivo": WordType.TRANSITIVE_VERB,
}

/**
 * Interface representing a word with its definitions, examples, type, translations, and optional language.
 */
export interface IWord {
  // add documentation for each property
  word: string;
  definitions: string[];
  // examples of the word in use
  examples: string[];
  // what kind of word it is
  type: WordType;
  // set of translations to the other available language, for example if the word is in Spanish, the translations will be in Palenque
  translations: string[];
  // word language
  language?: 'spanish' | 'palenque'
}