export const Action = {
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  RESTORE_USER: 'RESTORE_USER',
  SEARCH_USER: 'SEARCH_USER',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  RESTORE_ARTICLE: 'RESTORE_ARTICLE',
  SEARCH_ARTICLE: 'SEARCH_ARTICLE',
  CREATE_WORD: 'CREATE_WORD',
  UPDATE_WORD: 'UPDATE_WORD',
  DELETE_WORD: 'DELETE_WORD',
  RESTORE_WORD: 'RESTORE_WORD',
  SEARCH_WORD: 'SEARCH_WORD',
  ACCESS_ARTICLE: 'ACCESS_ARTICLE',
  ACCESS_WORD: 'ACCESS_WORD',
}

export type ActionType = keyof typeof Action;