export const Action = {
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',
  RESTORE_USER: 'RESTORE_USER',
  SEARCH_USER: 'SEARCH_USER',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  EDIT_ARTICLE: 'EDIT_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  RESTORE_ARTICLE: 'RESTORE_ARTICLE',
  SEARCH_ARTICLE: 'SEARCH_ARTICLE',
  CREATE_WORD: 'CREATE_WORD',
  EDIT_WORD: 'EDIT_WORD',
  DELETE_WORD: 'DELETE_WORD',
  RESTORE_WORD: 'RESTORE_WORD',
  SEARCH_WORD: 'SEARCH_WORD',
  VIEW_ARTICLE: 'VIEW_ARTICLE',
  VIEW_WORD: 'VIEW_WORD',
  VIEW_USER: 'VIEW_USER',
  SUPER_ADMIN: 'SUPER_ADMIN',
}

export type ActionType = keyof typeof Action;