export const ENTITLEMENTS = {
  EDIT_WORD: 'EDIT_WORD',
  CREATE_WORD: 'CREATE_WORD',
  DELETE_WORD: 'DELETE_WORD',
  VIEW_WORD: 'VIEW_WORD',
  EDIT_ARTICLE: 'EDIT_ARTICLE',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  VIEW_ARTICLE: 'VIEW_ARTICLE',
  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  VIEW_USER: 'VIEW_USER',
  UPDATE_USER: 'UPDATE_USER',
  RESTORE_USER: 'RESTORE_USER',
  NONE: 'NONE',
}

export type ENTITLEMENTS = keyof typeof ENTITLEMENTS;